apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: db
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
