version: '3'
# Version 3 requires a fairly new docker compose.

#
#networks:
#  #Due to me wanting the autonomous components (in another compose project) to link to these services, they must be on the same network
#  #Default creates a network for each project per default, so we must set the network explicitly
#  #But then it is not autocreated, so you must create it once with this command
#  #   docker network create domsNetwork
#  default:
#    external:
#      name: domsNetwork

services:
  db:
    image: postgres:9.4
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
    expose: #Meaning only accessible to linked containers
      - "5432"
    ports:
      - "15432:5432"
    userns_mode: host
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/:ro,Z
      - ./data/postgres/:/var/lib/postgresql/data/:rw,Z

  doms:
    build:
      context: ./
      dockerfile: docker/doms/Dockerfile.doms
    ports:
      - "7880:7880"
    volumes:
      - ./data/doms:/doms-data/:rw,U,Z
      - ./data/logs/:/logs/:rw,U,Z
    userns_mode: host
    links:
      - db
    depends_on:
      - db

  sboi:
    build: #Hardcoded config values that match the ones in doms above
      context: ./docker/sboi
      dockerfile: Dockerfile.sboi
    ports:
      - "58608:58608"
    userns_mode: host
    volumes:
      - ./data/sboi:/persistent/:rw,Z,U
    links:
      - doms
    depends_on:
      - doms

  zookeeper:
    build:
      context: ./docker/zookeeper
      dockerfile: Dockerfile.zookeeper
    image: kb/zookeeper
    ports:
      - "2181:2181"
    restart: always
    depends_on: []
