apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-config
data:
    "local-storage": |
      {
        "hostDir": "/mnt/local-storage/hdd",
        "mountDir": "/mnt/local-storage/hdd"
      }