apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --build build-config
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: db:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: docker/postgres/
    git:
      ref: openshift
      uri: git@github.com:statsbiblioteket/doms-installer.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile.db
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
