apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift --build build-config
    kompose.version: 1.6.0 (e4adfef)
  creationTimestamp: null
  labels:
    io.kompose.service: doms
  name: doms
spec:
  replicas: 1
  selector:
    io.kompose.service: doms
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: doms
    spec:
      containers:
      - image: ' '
        name: doms
        ports:
        - containerPort: 7880
        resources: {}
        volumeMounts:
        - mountPath: /doms-data/
          name: doms-claim0
      restartPolicy: Always
      volumes:
      - name: doms-claim0
        persistentVolumeClaim:
          claimName: doms-claim0
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - doms
      from:
        kind: ImageStreamTag
        name: doms:latest
    type: ImageChange
status: {}
