apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: doms
  name: doms
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: doms
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
