apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sboi
  name: sboi
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: sboi
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
