apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: doms-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage
status: {}
