TOMCAT_HTTPPORT=8080
TOMCAT_SHUTDOWNPORT=8005
TOMCAT_SSLPORT=8443
TOMCAT_AJPPORT=8009
FEDORAADMIN=fedoraAdmin
FEDORAADMINPASS=fedoraAdminPass

BITFINDER=http://bitfinder.statsbiblioteket.dk/
BITSTORAGE_SERVER=domstest@halley
BITSTORAGE_SCRIPT=bin/server.sh
