PORTRANGE=78
TOMCAT_SERVERNAME=localhost

FEDORAADMIN=fedoraAdmin
FEDORAADMINPASS=fedoraAdminPass

BITFINDER=http://bitfinder.statsbiblioteket.dk/
BITSTORAGE_SCRIPT="ssh doms@stage01 bin/server.sh"

USE_POSTGRESQL=true
DATABASE_NAME=doms-test$PORTRANGE
DATABASE_USERNAME=doms-test$PORTRANGE
DATABASE_PASSWORD=doms-test$PORTRANGE