TOMCAT_HTTPPORT=8080
TOMCAT_SHUTDOWNPORT=8005
TOMCAT_SSLPORT=8443
TOMCAT_AJPPORT=8009
TOMCAT_SERVERNAME=localhost

FEDORAADMIN=fedoraAdmin
FEDORAADMINPASS=fedoraAdminPass

BITFINDER=http://bitfinder.statsbiblioteket.dk/
BITSTORAGE_SCRIPT="ssh domstest@halley bin/server.sh"
