FROM maven:3.5.2-jdk-8

WORKDIR /root

COPY pom.xml .

RUN mvn -P!testbed,!vagrant --settings /usr/share/maven/ref/settings-docker.xml  org.apache.maven.plugins:maven-dependency-plugin:3.0.2:go-offline

COPY src /root/src
COPY docs /root/docs
COPY docker /root/docker

RUN mvn -P!testbed,!vagrant --settings /usr/share/maven/ref/settings-docker.xml -DskipTests package
